stages:
  - diff
  - build

# diff:
#   stage: diff
#   image: aergus/latex:2020-05-27
#   rules:
#     - changes:
#         - "paper/**/*"
#         - ".gitlab-ci.yml"
#       when: on_success
#     - if: $CI_COMMIT_BRANCH == 'master'
#   script:
#     - sh diff.sh
#   artifacts:
#     paths:
#       - diff/*

# paper_diff:
#   stage: build
#   image: aergus/latex:2020-05-27
#   needs:
#     - job: diff
#       artifacts: true

#   script:
#     - cd "diff/paper/"
#     - latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=. main | true
#     - ls -alh
#   artifacts:
#     paths:
#       - "diff/paper/main.pdf"
paper:
  stage: build
  image: aergus/latex:2020-05-27
  rules:
    - changes:
        - "Assignment/Hausarbeit/**/*"
        - ".gitlab-ci.yml"
      when: on_success
    - if: $CI_COMMIT_BRANCH == 'master'

  script:
    - cd "Assignment/Hausarbeit/"
    - sh build.sh
  artifacts:
    paths:
      - "Assignment/Hausarbeit/Hausarbeit.pdf"
