TIME_LIMIT=3600
./run_dw.sh Heuristic_Farkas Ins_4.cal $TIME_LIMIT
./run_dw.sh Heuristic_Farkas Ins_8.cal $TIME_LIMIT
./run_dw.sh Heuristic_Farkas Ins_12.cal $TIME_LIMIT
./run_dw.sh Heuristic_Farkas Ins_20.cal $TIME_LIMIT
./run_dw.sh Heuristic_Farkas Ins_30.cal $TIME_LIMIT
./run_dw.sh Heuristic_Farkas Ins_40.cal $TIME_LIMIT
./run_dw.sh Heuristic_Farkas Ins_50.cal $TIME_LIMIT
./run_dw.sh Heuristic_Farkas Ins_100.cal $TIME_LIMIT
./run_dw.sh Exact_Farkas Ins_4.cal $TIME_LIMIT
./run_dw.sh Exact_Farkas Ins_8.cal $TIME_LIMIT
./run_dw.sh Exact_Farkas Ins_12.cal $TIME_LIMIT
./run_dw.sh Exact_Farkas Ins_20.cal $TIME_LIMIT
./run_dw.sh Exact_Farkas Ins_30.cal $TIME_LIMIT
./run_dw.sh Exact_Farkas Ins_40.cal $TIME_LIMIT
./run_dw.sh Exact_Farkas Ins_50.cal $TIME_LIMIT
./run_dw.sh Exact_Farkas Ins_100.cal $TIME_LIMIT
./run_dw.sh Heuristic_ArtificialColumns Ins_4.cal $TIME_LIMIT
./run_dw.sh Heuristic_ArtificialColumns Ins_8.cal $TIME_LIMIT
./run_dw.sh Heuristic_ArtificialColumns Ins_12.cal $TIME_LIMIT
./run_dw.sh Heuristic_ArtificialColumns Ins_20.cal $TIME_LIMIT
./run_dw.sh Heuristic_ArtificialColumns Ins_30.cal $TIME_LIMIT
./run_dw.sh Heuristic_ArtificialColumns Ins_40.cal $TIME_LIMIT
./run_dw.sh Heuristic_ArtificialColumns Ins_50.cal $TIME_LIMIT
./run_dw.sh Heuristic_ArtificialColumns Ins_100.cal $TIME_LIMIT
./run_dw.sh Exact_ArtificialColumns Ins_4.cal $TIME_LIMIT
./run_dw.sh Exact_ArtificialColumns Ins_8.cal $TIME_LIMIT
./run_dw.sh Exact_ArtificialColumns Ins_12.cal $TIME_LIMIT
./run_dw.sh Exact_ArtificialColumns Ins_20.cal $TIME_LIMIT
./run_dw.sh Exact_ArtificialColumns Ins_30.cal $TIME_LIMIT
./run_dw.sh Exact_ArtificialColumns Ins_40.cal $TIME_LIMIT
./run_dw.sh Exact_ArtificialColumns Ins_50.cal $TIME_LIMIT
./run_dw.sh Exact_ArtificialColumns Ins_100.cal $TIME_LIMIT
